#!/usr/bin/env node
var moment = require('moment')
var builds = [{ 'owner': 'JI',
'device': 'Windows 7',
'type': 'API',
'product': 'UpdateCommentAndOutage',
'team': 'UpdateTeam',
'build': '1000',
'version': 'Latest',
'is_archive': false,
'start_time': moment().format(),
'end_time': moment().add(3, 'hour').format(),
'status': {
  'pass': 4,
  'fail': 5,
  'skip': 5,
  'warning': 6
},
'comments': [{
  'user': 'Super user',
  'message': 'this is just a message.',
  'time': moment().add(4, 'hour').format()
}],
'outages': [{
  'pattern': 'timeout exception',
  'search_type': 'STRING',
  'caused_by': '',
  'tracking' : {
    'number' : 'JIRA-2234'
  },
  'exceptions': [
    'TEST222', 'TES111'
  ],
  'impact_test':{
    'fail' : 11,
    'skip' : 20,
    'warning' : 11
  }
}]
},
  { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'UpdateProduct',
    'team': 'UpdateTeam',
    'build': '1000',
    'version': 'Latest',
    'is_archive': false,
    'start_time': moment().format(),
    'end_time': moment().add(3, 'hour').format(),
    'status': {
      'pass': 10,
      'fail': 9,
      'skip': 11,
      'warning': 12
    },
    'comments': [{
      'user': 'Super user',
      'message': 'this is just a message.',
      'time': moment().add(4, 'hour').format()
    }],
    'outages': [{
      'pattern': 'Nullpointer exception',
      'search_type': 'STRING',
      'caused_by': '',
      'tracking' : {
        'number' : 'JIRA-1234'
      },
      'exceptions': [
        'TEST1234', 'TEST1235'
      ],
      'impact_test':{
        'fail' : 10,
        'skip' : 2,
        'warning' : 1
      }
    }]
  },
  { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'UpdateComment',
    'team': 'UpdateTeam',
    'build': '1000',
    'version': 'Latest',
    'is_archive': false,
    'start_time': moment().format(),
    'end_time': moment().add(3, 'hour').format(),
    'status': {
      'pass': 10,
      'fail': 9,
      'skip': 11,
      'warning': 12
    }
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'uReport',
    'team': 'Team1',
    'build': '1',
    'version': '1.0',
    'is_archive': false,
    'start_time': moment().format(),
    'end_time': moment().add(3, 'hour').format()
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'uReport',
    'team': 'Team1',
    'build': '2',
    'version': '1.0',
    'is_archive': false,
    'start_time': moment().subtract(10, 'days').format(),
    'end_time': moment().subtract(10, 'days').add(3, 'hour').format()
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'uReport',
    'team': 'Team1',
    'build': '3',
    'version': '1.0',
    'is_archive': false,
    'start_time': moment().subtract(15, 'days').format(),
    'end_time': moment().subtract(15, 'days').add(3, 'hour').format()
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'uReport',
    'team': 'Team1',
    'build': '4',
    'version': '1.0',
    'is_archive': false,
    'start_time': moment().subtract(30, 'days').format(),
    'end_time': moment().subtract(30, 'days').add(1, 'hour').format()
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'uReport',
    'team': 'Team1',
    'build': '5',
    'version': '1.0',
    'is_archive': false,
    'start_time': moment().subtract(40, 'days').format(),
    'end_time': moment().subtract(40, 'days').add(3, 'hour').format()
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'uReport',
    'team': 'Team1',
    'build': '6',
    'version': '1.0',
    'is_archive': false,
    'start_time': moment().subtract(60, 'days').format(),
    'end_time': moment().subtract(60, 'days').add(2, 'hour').format()
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'uReport',
    'team': 'Team1',
    'build': '7',
    'version': '1.0',
    'is_archive': false,
    'start_time': moment().subtract(61, 'days').format(),
    'end_time': moment().subtract(61, 'days').add(3, 'hour').format()
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'API',
    'product': 'uReport',
    'team': 'Team1',
    'build': '8',
    'version': '1.0',
    'is_archive': false,
    'start_time': moment().subtract(70, 'days').format(),
    'end_time': moment().subtract(70, 'days').add(5, 'hour').format()
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'UI',
    'product': 'uReport',
    'team': 'Team2',
    'build': '10',
    'version': '2.0',
    'is_archive': true,
    'start_time': '2017-07-30T16:19:11.931-04:00',
    'end_time': '2017-07-30T16:58:37.722-04:00',
    'browser': 'chrome',
    'settings': {
      'param1': 'value1',
      'param2': 'value2',
      'param3': 'value3',
      'param4': 'value4',
      'param5': 'value5'
    }
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'UI',
    'product': 'uReport',
    'team': 'Team2',
    'build': '1',
    'version': '2.0',
    'is_archive': false,
    'start_time': moment().format(),
    'end_time': moment().add(3, 'hour').format(),
    'browser': 'IE'
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'UI',
    'product': 'uReport',
    'team': 'Team2',
    'build': '2',
    'version': '2.0',
    'is_archive': false,
    'start_time': moment().subtract(10, 'days').format(),
    'end_time': moment().subtract(10, 'days').add(3, 'hour').format(),
    'browser': 'IE'
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'UI',
    'product': 'uReport',
    'team': 'Team2',
    'build': '3',
    'version': '2.0',
    'is_archive': false,
    'start_time': moment().subtract(15, 'days').format(),
    'end_time': moment().subtract(15, 'days').add(3, 'hour').format(),
    'browser': 'ie'
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'UI',
    'product': 'uReport',
    'team': 'Team2',
    'build': '1',
    'version': '2.0',
    'is_archive': false,
    'start_time': moment().format(),
    'end_time': moment().add(3, 'hour').format(),
    'browser': 'chrome'
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'UI',
    'product': 'uReport',
    'team': 'Team2',
    'build': '2',
    'version': '2.0',
    'is_archive': false,
    'start_time': moment().subtract(10, 'days').format(),
    'end_time': moment().subtract(10, 'days').add(3, 'hour').format(),
    'browser': 'chrome'
  }, { 'owner': 'JI',
    'device': 'iPhoneX',
    'type': 'UI',
    'product': 'uReport',
    'team': 'Team2',
    'build': '3',
    'version': '2.0',
    'is_archive': false,
    'start_time': moment().subtract(15, 'days').format(),
    'end_time': moment().subtract(15, 'days').add(3, 'hour').format(),
    'browser': 'chrome'
  }, { 'owner': 'JI',
    'device': 'Windows 7',
    'type': 'UI',
    'product': 'uReport',
    'team': 'Team2',
    'build': '4',
    'version': '2.1',
    'is_archive': false,
    'start_time': moment().subtract(16, 'days').format(),
    'end_time': moment().subtract(16, 'days').add(3, 'hour').format(),
    'browser': 'chrome'
  }
]
module.exports = builds
